--------------------------------------------------------
--  Arquivo criado - quinta-feira-abril-30-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MANUTENCAO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MANUTENCAO" 
   (	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DATA_AGENDADA" DATE, 
	"DATA_REALIZADA" DATE, 
	"DESCRICAO" VARCHAR2(255 CHAR), 
	"STATUS_MANUTENCAO" VARCHAR2(255 CHAR), 
	"TIPO_MANUTENCAO" VARCHAR2(255 CHAR), 
	"SISTEMA_ID" NUMBER(19,0), 
	"TECNICO_ID" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SISTEMA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."SISTEMA" 
   (	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DATA_PROXIMA_MANUTENCAO" DATE, 
	"DATA_ULTIMA_MANUTENCAO" DATE, 
	"NOME" VARCHAR2(255 CHAR), 
	"TIPO_SISTEMA" VARCHAR2(255 CHAR), 
	"CLIENTE_ID" NUMBER(19,0), 
	"DATA_CADASTRO" DATE, 
	"IS_DISPONIVEL" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTE" 
   (	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LOCALIDADE" VARCHAR2(255 CHAR), 
	"NOME" VARCHAR2(255 CHAR), 
	"CNPJ" VARCHAR2(255 CHAR), 
	"DATA_INICIO_CONTRATO" DATE, 
	"DURACAO_CONTRATO" NUMBER(10,0), 
	"EMAIL_RESPONSAVEL" VARCHAR2(255 CHAR), 
	"IS_ATIVO" NUMBER(1,0), 
	"NOME_RESPONSAVEL" VARCHAR2(255 CHAR), 
	"TELEFONE_RESPONSAVEL" VARCHAR2(255 CHAR), 
	"DATA_FIM_CONTRATO" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TECNICO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TECNICO" 
   (	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(255 CHAR), 
	"NOME" VARCHAR2(255 CHAR), 
	"TELEFONE" VARCHAR2(255 CHAR), 
	"NIVEL" VARCHAR2(255 CHAR), 
	"IS_ATIVO" NUMBER(1,0), 
	"SENHA" VARCHAR2(255 CHAR), 
	"ROLE" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MANUTENCAO
SET DEFINE OFF;
REM INSERTING into SYSTEM.SISTEMA
SET DEFINE OFF;
Insert into SYSTEM.SISTEMA (ID,DATA_PROXIMA_MANUTENCAO,DATA_ULTIMA_MANUTENCAO,NOME,TIPO_SISTEMA,CLIENTE_ID,DATA_CADASTRO,IS_DISPONIVEL) values ('31',null,null,null,null,'26',to_date('27/04/26','DD/MM/RR'),'1');
Insert into SYSTEM.SISTEMA (ID,DATA_PROXIMA_MANUTENCAO,DATA_ULTIMA_MANUTENCAO,NOME,TIPO_SISTEMA,CLIENTE_ID,DATA_CADASTRO,IS_DISPONIVEL) values ('32',null,null,null,null,'26',to_date('27/04/26','DD/MM/RR'),'1');
Insert into SYSTEM.SISTEMA (ID,DATA_PROXIMA_MANUTENCAO,DATA_ULTIMA_MANUTENCAO,NOME,TIPO_SISTEMA,CLIENTE_ID,DATA_CADASTRO,IS_DISPONIVEL) values ('33',null,null,'BAL-4754','BALAO','47',to_date('27/04/26','DD/MM/RR'),'1');
Insert into SYSTEM.SISTEMA (ID,DATA_PROXIMA_MANUTENCAO,DATA_ULTIMA_MANUTENCAO,NOME,TIPO_SISTEMA,CLIENTE_ID,DATA_CADASTRO,IS_DISPONIVEL) values ('29',null,null,null,null,'47',to_date('27/04/26','DD/MM/RR'),'1');
Insert into SYSTEM.SISTEMA (ID,DATA_PROXIMA_MANUTENCAO,DATA_ULTIMA_MANUTENCAO,NOME,TIPO_SISTEMA,CLIENTE_ID,DATA_CADASTRO,IS_DISPONIVEL) values ('30',null,null,null,null,'26',to_date('27/04/26','DD/MM/RR'),'1');
REM INSERTING into SYSTEM.CLIENTE
SET DEFINE OFF;
Insert into SYSTEM.CLIENTE (ID,LOCALIDADE,NOME,CNPJ,DATA_INICIO_CONTRATO,DURACAO_CONTRATO,EMAIL_RESPONSAVEL,IS_ATIVO,NOME_RESPONSAVEL,TELEFONE_RESPONSAVEL,DATA_FIM_CONTRATO) values ('47','Rio de Janeiro-RJ','Petrobras','33.222.333/0001-99',to_date('20/04/26','DD/MM/RR'),'36','marocs.souza@petrobras.com','1','Marcos Souza','(21) 98798-7987',null);
Insert into SYSTEM.CLIENTE (ID,LOCALIDADE,NOME,CNPJ,DATA_INICIO_CONTRATO,DURACAO_CONTRATO,EMAIL_RESPONSAVEL,IS_ATIVO,NOME_RESPONSAVEL,TELEFONE_RESPONSAVEL,DATA_FIM_CONTRATO) values ('66','São José dos Campos','Jackson Moraes','99.888.899/0001-23',to_date('23/04/26','DD/MM/RR'),'13','jacksontmoraes@gmail.com','1','fdfdsfa','(12) 99135-7585',null);
Insert into SYSTEM.CLIENTE (ID,LOCALIDADE,NOME,CNPJ,DATA_INICIO_CONTRATO,DURACAO_CONTRATO,EMAIL_RESPONSAVEL,IS_ATIVO,NOME_RESPONSAVEL,TELEFONE_RESPONSAVEL,DATA_FIM_CONTRATO) values ('26','Belo Horizonte - MG','Vale do Rio Doce','22.222.222/0001-22',null,null,null,'1',null,null,null);
Insert into SYSTEM.CLIENTE (ID,LOCALIDADE,NOME,CNPJ,DATA_INICIO_CONTRATO,DURACAO_CONTRATO,EMAIL_RESPONSAVEL,IS_ATIVO,NOME_RESPONSAVEL,TELEFONE_RESPONSAVEL,DATA_FIM_CONTRATO) values ('46','Mariana-MG','Samarco','11.231.123/0001-99',null,null,'antonio@samarco.com','1','Antonio ','(31) 99876-5433',null);
REM INSERTING into SYSTEM.TECNICO
SET DEFINE OFF;
Insert into SYSTEM.TECNICO (ID,EMAIL,NOME,TELEFONE,NIVEL,IS_ATIVO,SENHA,ROLE) values ('9','admin@admin','admin','12998787877','PLENO','1','123456','ADMIN');
Insert into SYSTEM.TECNICO (ID,EMAIL,NOME,TELEFONE,NIVEL,IS_ATIVO,SENHA,ROLE) values ('10','lu@teste.com','Luciaaa','(12) 98766-6767','JUNIOR','1','123456','TECNICO');
