services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: agenda-db
    ports:
      - "1522:1521"   # Porta padrão do Oracle Listener
      - "5500:5500"   # Porta para Oracle EM Express
    environment:
      ORACLE_PASSWORD: "admin123"   # Defina a senha do usuário SYS, SYSTEM e PDBADMIN
    volumes:
      - oracle-data:/opt/oracle/oradata  # Persistência dos dados

volumes:
  oracle-data: