spring.application.name=dataagenda

spring.datasource.url=jdbc:oracle:thin:@dataagendadb_high?TNS_ADMIN=/home/ubuntu/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Jtmj@@@200276
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

server.error.include-message=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=datatechapi@gmail.com
spring.mail.password=zhrp dhuv dogu irxm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:oracle:thin:@localhost:1522/xepdb1
spring.datasource.username=system
spring.datasource.password=admin123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

